baseURL = 'https://clio.hpc4ai.it/'
languageCode = 'en-us'
title = 'CLIO'
theme='relearn'

[params]
  themeVariant = 'neon'

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> CLIO on github"
identifier = "clio"
url = "https://github.com/High-Performance-IO/clio"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> CAPIO"
identifier = "capio"
url = "https://github.com/High-Performance-IO/capio"
weight = 11
